---
id: night_mode
alias: Night Mode
description: Turns night_time to on when current time is night
mode: single
trigger:
  - platform: time_pattern
    seconds: /10
action:
  - if:
      - condition: time
        after: "17:30:00"
        before: "06:00:00"
    then:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.night_time
    else:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.night_time