---
services:
  hass:
    image: ghcr.io/onedr0p/home-assistant:2024.4.3
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/config
    ports:
      - 8123:8123
    user: 1000:1000