default_config:
  
homeassistant:
  name: Ajeng's Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Asia/Makassar
  packages: !include_dir_named packages

device_tracker:
wake_on_lan:
