- platform: mqtt
  unique_id: mbr_speaker
  name: "Speaker"
  state_topic: mbr-panel/stat/RESULT
  value_template: "{{ value_json.POWER2 }}"
  command_topic: mbr-panel/cmnd/POWER2
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false
  availability_topic: mbr-panel/tele/LWT
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  unique_id: mbr_htpc
  name: "HTPC Switch"
  state_topic: mbr-panel/stat/RESULT
  value_template: "{{ value_json.POWER3 }}"
  command_topic: mbr-panel/cmnd/POWER3
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false
  availability_topic: mbr-panel/tele/LWT
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  unique_id: mbr_tv
  name: "TV"
  state_topic: mbr-panel/stat/RESULT
  value_template: "{{ value_json.POWER4 }}"
  command_topic: mbr-panel/cmnd/POWER4
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false
  availability_topic: mbr-panel/tele/LWT
  payload_available: "Online"
  payload_not_available: "Offline"