automation:
- id: auto_mbr_bedroom
  alias: "Lampu Kamar Auto OFF"
  trigger:
    platform: state
    entity_id: light.bedroom
  condition:
    - condition: time
      after: '18:00:00'
      before: '06:00:00'
  action:
    - entity_id: light.bedroom_ambilight
      service_template: >-
       {% if is_state('light.mbr_main', 'on') %}
        light.turn_off
       {% else %}
        light.turn_on
       {% endif %}

       