default_config:
  
homeassistant:
  name: Ajeng's Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Asia/Makassar
  packages: !include_dir_named packages

device_tracker: 

mqtt:
  discovery: false
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device
#sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
climate: !include_dir_merge_list climate
#scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
light: !include_dir_merge_list light
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
media_player: !include_dir_merge_list media

mikrotik:
  - host: !secret ares_host
    username: !secret ares_username
    password: !secret ares_password
    arp_ping: true
    method: dhcp
    track_devices: true

cloud:
  google_actions:
    filter:
      include_domains:
      - light
      - climate
      include_entities:
      - media_player.htpc
    entity_config:
      media_player.htpc:
        name: TV
        room: Main Room