- platform: mqtt
  name: "AC Kamar"
  unique_id: mbr_ac
  availability_topic: "remote1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

  action_topic: "mbr/ac/state"
  action_template: >-
    {% if value_json.mode == "cool" %}
      cooling
    {% elif value_json.mode == "fan_only" %}
      drying
    {% else %}
      off
    {% endif %}
  
  power_command_topic: "mbr/ac/power"
  mode_command_topic: "mbr/ac/mode"
  mode_state_topic: "mbr/ac/state"
  mode_state_template: "{{ value_json.mode }}"
  modes: 
    - "cool"
    - "off"
    - "fan_only"
    #- "ai"
    #- "dehumidifier"
  
  
  # temperature
  temperature_command_topic: "mbr/ac/temperature"
  current_temperature_topic: "mbr/ac/state"
  current_temperature_template: "{{ value_json.temperature }}"
  precision: 0.1
  temp_step: 1
  min_temp: 18
  max_temp: 30
  initial: 27
  
  # fan section
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"
  fan_mode_state_topic: "mbr/ac/state"
  fan_mode_state_template: "{{ value_json.fan }}"
  fan_mode_command_topic: "mbr/ac/fan"

  # swing section
  swing_modes:
    - "on"
    - "off"
  swing_mode_state_topic: "mbr/ac/state"
  swing_mode_state_template: "{{ value_json.swing }}"
  swing_mode_command_topic: "mbr/ac/swing"
  