---
id: mbr_ac_eco
alias: AC Eco
description: Set Eco Mode
mode: single
trigger:
  - platform: state
    entity_id: input_boolean.mbr_ac_eco
action:
  - service: script.mqtt_irsend
    data_template:
      payload: >-
        {% set state = states('input_boolean.mbr_ac_eco') %}
        {% if state %}
          {"Protocol":"LG","Bits":28,"Data":"0x8810045","DataLSB":"0x108100A2","Repeat":0}
        {% else %}
          {"Protocol":"LG","Bits":28,"Data":"0x8810056","DataLSB":"0x1081006A","Repeat":0}
        {% endif %}