toggle_automation:
  alias: "Toggle Automation"
  mode: single
  icon: mdi:remote
  sequence:
    - variables:
        all: >
          {{ 
            states.automation
            | map(attribute='entity_id')
            | reject('eq', 'automation.disable_automation') 
            | reject('eq', 'automation.night_mode')
            | list 
          }}
    - if:
        - condition: state
          entity_id: binary_sensor.energy_homelab
          state: "off"
      then:
        - service: automation.turn_on
          target:
            entity_id: "{{all}}"
        - service: script.node_suspend
          data:
            host: hera.lan
        - service: script.node_suspend
          data:
            host: mars.lan
        - service: script.node_suspend
          data:
            host: iris.lan
      else:
        - service: automation.turn_off
          target:
            entity_id: "{{all}}"
        - service: script.turn_on_hera
        - service: script.turn_on_mars
        - service: script.turn_on_iris