climate:
- platform: mqtt
  name: "AC Kamar"
  unique_id: mbr_ac
  availability_topic: "remote1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

  #payload_on: 'on'
  #payload_off: 'off'
  power_command_topic: "mbr/ac/power"
  power_state_topic: "mbr/ac/power/state"
  #power_state_template: "{{ value_json }}"
  #action_topic: "mbr/ac/tele"
  #action_template: >-
  #  {% if value_json.power == 'off' %}
  #    off
  #  {% elif value_json.mode == 'cool' %}
  #    cooling
  #  {% elif value_json.mode == 'dry' %}
  #    drying
  #  {% elif value_json.mode == 'auto' %}
  #    auto
  #  {% else %}
  #    fan_only
  #  {% endif %}
  mode_command_topic: "mbr/ac/mode"
  mode_state_topic: "mbr/ac/mode/state"
  #mode_state_template: "{{ value_json }}"
  modes: 
    - "off"
    - auto
    - cool
    - dry
    - fan_only
  
  
  # temperature
  temperature_command_topic: "mbr/ac/temperature"
  current_temperature_topic: "mbr/ac/temperature/state"
  #current_temperature_template: "{{ value_json }}"
  precision: 0.1
  temp_step: 1
  min_temp: 18
  max_temp: 30
  initial: 27
  
  # fan section
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"
  fan_mode_state_topic: "mbr/ac/fan/state"
  #fan_mode_state_template: "{{ value_json }}"
  fan_mode_command_topic: "mbr/ac/fan"

  # swing section
  swing_modes:
    - "on"
    - "off"
  swing_mode_state_topic: "mbr/ac/swing/state"
  #swing_mode_state_template: "{{ value_json }}"
  swing_mode_command_topic: "mbr/ac/swing"
  
switch:
  - platform: mqtt
    name: "Power"
    unique_id: "mbr_ac_power"
    state_topic: "mbr/ac/power/state"
    #value_template: "{{ value_json.energy_saving }}"
    command_topic: "mbr/ac/power"
    payload_on: "on"
    payload_off: "off"
    availability_topic: remote1/tele/LWT
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Thermo Energy Saving"
    unique_id: "thermo_saving"
    state_topic: "mbr/ac/energy_saving/state"
    #value_template: "{{ value_json.energy_saving }}"
    command_topic: "mbr/ac/energy_saving"
    payload_on: "on"
    payload_off: "off"
    availability_topic: remote1/tele/LWT
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Thermo Autoclean"
    unique_id: "thermo_autoclean"
    state_topic: "mbr/ac/autoclean/state"
    #value_template: "{{ value_json.autoclean }}"
    command_topic: "mbr/ac/autoclean"
    payload_on: "on"
    payload_off: "off"
    availability_topic: remote1/tele/LWT
    payload_available: "Online"
    payload_not_available: "Offline"