automation: !include_dir_list automations/
script: !include_dir_merge_named scripts/
shell_command: !include_dir_merge_named shell/
light: !include_dir_list devices/lights/
switch: !include_dir_list devices/switches/
sensor: !include_dir_list sensors/
utility_meter: !include_dir_merge_named devices/utility-meter
climate: !include_dir_list devices/climate/
mqtt: !include_dir_merge_named devices/mqtt/

input_boolean: !include_dir_merge_named devices/booleans/

# binary_sensor: !include_dir_merge_list devices/binary/
input_text: !include_dir_merge_named devices/text/
input_select: !include_dir_merge_named devices/selects